"""Draft documents built from the intake answers and findings.

Each document is a list of blocks. The same blocks render to the HTML review
preview and to the exported .docx, so the reviewer approves exactly what gets
exported. Templates here decide structure only; the content comes from the
engagement.
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field
from datetime import date

from docx import Document as DocxDocument

from grc_agent.assessment import readiness_score
from grc_agent.discovery import catalog
from grc_agent.register import Register

DOCUMENT_TYPES = {
    "gap_report": "Gap assessment report",
    "ropa": "Record of processing activities",
    "privacy_notice": "Privacy notice",
    "breach_playbook": "Breach response playbook",
    "dpa": "Data processing agreement",
}

DRAFT_BANNER = "DRAFT: generated by GRC Flow. A consultant must review it before it's sent."
SELF_BANNER = (
    "DRAFT: generated by GRC Flow. Have your Data Protection Officer or legal adviser review "
    "it before you rely on it."
)
DPA_BANNER = (
    "DRAFT FOR LAWYER: not client-ready without legal sign-off. Contract terms here are a "
    "starting point only."
)
STATUS_LABELS = {
    "gap": "Gap",
    "compliant": "Compliant",
    "open_item": "Open item",
    "not_applicable": "Not applicable",
}
LEGAL_BASES = {"consent": "Consent (Section 6)", "legitimate_use": "Legitimate use (Section 7)"}
LOCATIONS = {"india": "India", "outside": "Outside India", "both": "India and outside India"}
CONTRACTS = {"signed": "Signed", "negotiating": "Being negotiated", "none": "None"}


@dataclass
class Block:
    kind: str  # h1 | h2 | h3 | p | bullets | table | warning
    text: str = ""
    items: list[str] = field(default_factory=list)
    headers: list[str] = field(default_factory=list)
    rows: list[list[str]] = field(default_factory=list)


@dataclass(frozen=True)
class EngagementFacts:
    """Everything a document may draw on. Only the intake and findings are required:
    the registers make the documents specific, and each document falls back to the
    intake answers when a register is still empty."""

    client: str
    sector: str
    answers: dict[str, str]
    findings: list[
        dict
    ]  # rows with obligation_id, status, severity, citation, summary, remediation
    audience: str = "client"  # client | self (see AUDIENCES in web/app.py)
    inventory: list[dict] = field(default_factory=list)  # data_inventory rows
    vendors: list[dict] = field(default_factory=list)  # vendor register: ref + data fields
    dpias: list[dict] = field(default_factory=list)  # DPIA register: ref + data fields

    @property
    def own(self) -> bool:
        return self.audience == "self"


def build_document(kind: str, facts: EngagementFacts, register: Register) -> list[Block]:
    builders = {
        "gap_report": _gap_report,
        "ropa": _ropa,
        "privacy_notice": _privacy_notice,
        "breach_playbook": _breach_playbook,
        "dpa": _dpa,
    }
    banner = DPA_BANNER if kind == "dpa" else SELF_BANNER if facts.own else DRAFT_BANNER
    blocks = [
        Block("h1", f"{DOCUMENT_TYPES[kind]}: {facts.client}"),
        Block("warning", banner),
        Block("p", f"Prepared {date.today():%d %B %Y}. Register version {register.version}."),
    ]
    return blocks + builders[kind](facts, register)


def _answer(facts: EngagementFacts, question_id: str, fallback: str = "[Not provided]") -> str:
    value = (facts.answers.get(question_id) or "").strip()
    return value or fallback


def _split_top_level(text: str, separators: str) -> list[str]:
    """Split on any of `separators`, but never inside brackets."""
    parts, depth, current = [], 0, []
    for ch in text:
        depth += ch in "([{"
        depth -= ch in ")]}" and depth > 0
        if ch in separators and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    parts.append("".join(current))
    return parts


def _lines(text: str) -> list[str]:
    """Turn a free-text answer into bullet points a reader can follow.

    One bullet per line, sentence or semicolon. A piece that introduces a list
    ("Parents: name, phone, email") stays whole; a plain comma list becomes one bullet
    per item. Commas inside brackets never split.
    """
    pieces = []
    for line in text.splitlines():
        for part in _split_top_level(line.replace(". ", ".\n"), ";\n"):
            part = part.strip(" -•\t.")
            if not part:
                continue
            if ":" in part:
                pieces.append(part)
            else:
                pieces += [p.strip(" -•\t.") for p in _split_top_level(part, ",")]
    return [p for p in pieces if p] or ["[Not provided]"]


def _kind_label(kind: str) -> str:
    entry = catalog.KINDS.get(kind)
    return entry.label if entry else kind.replace("_", " ").title()


def _join(values) -> str:
    seen = []
    for v in values:
        if v and v not in seen:
            seen.append(v)
    return ", ".join(seen)


def _where(vendor: dict) -> str:
    """Where a vendor processes data: 'Outside India · United States'."""
    place = LOCATIONS.get(vendor.get("location", ""), "Location not known")
    countries = (vendor.get("countries") or "").strip()
    if countries.lower().startswith(place.lower()):  # "India (Mumbai)" already says it
        return countries
    return " · ".join(x for x in (place, countries) if x)


def _gap_report(facts: EngagementFacts, register: Register) -> list[Block]:
    findings = facts.findings
    counts = {s: sum(f["status"] == s for f in findings) for s in STATUS_LABELS}
    score = readiness_score(findings)
    who = (
        "you skipped or weren't sure about"
        if facts.own
        else "the client skipped or wasn't sure about"
    )
    blocks = [
        Block("h2", "Summary"),
        Block(
            "p",
            f"Sector: {facts.sector}. Readiness score: "
            f"{'n/a' if score is None else f'{score}/100'}. "
            f"{counts['gap']} gap(s), {counts['open_item']} open item(s), "
            f"{counts['compliant']} compliant, {counts['not_applicable']} not applicable.",
        ),
        Block("p", f"Open items are questions {who}. They are not passes and need follow-up."),
    ]
    obligations = {o.id: o for o in register.obligations}
    for severity in ("critical", "high", "medium", "low"):
        rows = [
            [
                f["obligation_id"],
                obligations[f["obligation_id"]].obligation,
                STATUS_LABELS[f["status"]],
                f["citation"],
                f["remediation"] or "-",
            ]
            for f in findings
            if f["severity"] == severity and f["status"] in {"gap", "open_item"}
        ]
        if rows:
            blocks.append(Block("h2", f"{severity.title()} severity"))
            blocks.append(
                Block(
                    "table",
                    headers=["ID", "Obligation", "Status", "Provision", "Next step"],
                    rows=rows,
                )
            )
    return blocks


def _activities(facts: EngagementFacts) -> list[tuple[str, list[dict]]]:
    """Inventory records grouped into processing activities by their purpose."""
    groups: dict[str, list[dict]] = {}
    for row in facts.inventory:
        purpose = (row.get("purpose") or "").strip() or "Purpose not recorded yet"
        groups.setdefault(purpose, []).append(row)
    return sorted(groups.items(), key=lambda kv: kv[0] == "Purpose not recorded yet")


def _ropa(facts: EngagementFacts, register: Register) -> list[Block]:
    blocks = [
        Block("h2", "Data Fiduciary"),
        Block(
            "table",
            headers=["Item", "Details"],
            rows=[
                ["Organisation", f"{facts.client} ({facts.sector})"],
                ["Contact for data questions (Section 8(9))", _answer(facts, "INFO-CONTACT")],
                ["Children's data (Section 9)", _yes_no(facts, "CTX-CHILDREN")],
                ["Services outside India (Section 16)", _yes_no(facts, "CTX-FOREIGN")],
            ],
        ),
        Block("h2", "Processing activities"),
    ]
    gaps = []
    if facts.inventory:
        vendors_by_name = {v["name"].lower(): v for v in facts.vendors if v.get("name")}
        for n, (purpose, rows) in enumerate(_activities(facts), start=1):
            high = [_kind_label(r["kind"]) for r in rows if r.get("risk") == "high"]
            children = any(r.get("children") for r in rows)
            bases = _join(LEGAL_BASES.get(r.get("legal_basis") or "", "Not decided") for r in rows)
            shared = _join(r.get("recipients") for r in rows) or "Not recorded"
            abroad = [
                v["name"]
                for name, v in vendors_by_name.items()
                if name in shared.lower() and v.get("location") in ("outside", "both")
            ]
            blocks += [
                Block("h3", f"PA-{n:02d}: {purpose}"),
                Block(
                    "table",
                    headers=["Item", "Details"],
                    rows=[
                        ["Purpose (Section 5)", purpose],
                        ["Whose data", _join(r.get("principals") for r in rows) or "Not recorded"],
                        [
                            "Personal data",
                            _join(f"{_kind_label(r['kind'])} ({r['field']})" for r in rows),
                        ],
                        ["High-risk data", _join(high) or "None"],
                        [
                            "Children's data",
                            "Yes: verifiable parental consent needed (Section 9(1))"
                            if children
                            else "No",
                        ],
                        ["Lawful ground", bases],
                        [
                            "Where it is stored",
                            _join(r.get("storage_location") for r in rows) or "Not recorded",
                        ],
                        ["Shared with", shared],
                        ["Outside India", _join(abroad) or "None recorded"],
                        [
                            "Retention (Section 8(7))",
                            _join(r.get("retention") for r in rows) or "Not set",
                        ],
                        ["Owner", _join(r.get("owner") for r in rows) or "Not assigned"],
                        ["Source", _join(r.get("source_name") for r in rows)],
                    ],
                ),
            ]
            for r in rows:
                missing = [
                    label
                    for key, label in (
                        ("purpose", "purpose"),
                        ("legal_basis", "lawful ground"),
                        ("retention", "retention period"),
                        ("owner", "owner"),
                    )
                    if not (r.get(key) or "").strip()
                ]
                if missing:
                    gaps.append(f"{r['source_name']} · {r['field']}: no {', '.join(missing)}.")
    else:
        blocks += [
            Block(
                "table",
                headers=["Item", "Details from intake"],
                rows=[
                    ["Personal data collected", _answer(facts, "INFO-DATA")],
                    ["Purposes", _answer(facts, "INFO-PURPOSE")],
                    ["Tools and processors", _answer(facts, "INFO-TOOLS")],
                    ["Retention", _answer(facts, "INFO-RETENTION")],
                ],
            ),
        ]
        gaps.append(
            "No data inventory yet: scan or add your systems under Personal data, and this "
            "record will list one activity per purpose."
        )

    blocks.append(Block("h2", "Processors and recipients (Section 8(2))"))
    if facts.vendors:
        blocks.append(
            Block(
                "table",
                headers=[
                    "Ref",
                    "Processor",
                    "Service",
                    "Data shared",
                    "Where",
                    "Contract",
                    "Next review",
                ],
                rows=[
                    [
                        v.get("ref", ""),
                        v.get("name", ""),
                        v.get("service", "") or "-",
                        v.get("data_shared", "") or "-",
                        _where(v),
                        CONTRACTS.get(v.get("contract", ""), "Unknown"),
                        v.get("next_review", "") or "-",
                    ]
                    for v in facts.vendors
                ],
            )
        )
        gaps += [
            f"{v.get('ref', '')} {v.get('name', '')}: no signed contract."
            for v in facts.vendors
            if v.get("contract") != "signed"
        ]
    else:
        blocks.append(Block("p", f"From the intake: {_answer(facts, 'INFO-TOOLS')}"))
        gaps.append("No vendor register yet: add each processor under Vendors.")

    if facts.dpias:
        blocks += [
            Block("h2", "Impact assessments"),
            Block(
                "table",
                headers=["Ref", "Activity", "Residual risk", "Review by"],
                rows=[
                    [
                        d.get("ref", ""),
                        d.get("activity", ""),
                        (d.get("residual_risk") or "-").title(),
                        d.get("review_by", "") or "-",
                    ]
                    for d in facts.dpias
                ],
            ),
        ]
    blocks.append(Block("h2", "Gaps in this record"))
    blocks.append(
        Block(
            "bullets",
            items=gaps
            or ["None: every record has a purpose, lawful ground, retention period and owner."],
        )
    )
    return blocks


def _privacy_notice(facts: EngagementFacts, register: Register) -> list[Block]:
    if facts.inventory:
        by_whom: dict[str, list[str]] = {}
        for r in facts.inventory:
            by_whom.setdefault(r.get("principals") or "People we deal with", []).append(
                _kind_label(r["kind"])
            )
        collect = [f"{who}: {_join(kinds)}" for who, kinds in by_whom.items()]
        purposes = [
            purpose for purpose, _ in _activities(facts) if purpose != "Purpose not recorded yet"
        ]
        retention = [
            f"{_kind_label(r['kind'])}: {r['retention']}"
            for r in facts.inventory
            if (r.get("retention") or "").strip()
        ]
    else:
        collect = _lines(_answer(facts, "INFO-DATA"))
        purposes = _lines(_answer(facts, "INFO-PURPOSE"))
        retention = []
    shared = (
        [f"{v.get('service') or v.get('name')} ({_where(v)})" for v in facts.vendors]
        if facts.vendors
        else None
    )
    blocks = [
        Block("h2", "What we collect"),
        Block("bullets", items=collect),
        Block("h2", "Why we use it"),
        Block("bullets", items=purposes or _lines(_answer(facts, "INFO-PURPOSE"))),
        Block("h2", "Who we share it with"),
        Block("bullets", items=shared) if shared else Block("p", _answer(facts, "INFO-TOOLS")),
        Block("h2", "How long we keep it"),
        Block("bullets", items=retention)
        if retention
        else Block("p", _answer(facts, "INFO-RETENTION")),
    ]
    if facts.answers.get("CTX-CHILDREN") == "yes":
        blocks += [
            Block("h2", "Children"),
            Block(
                "p",
                "If you are under 18, we need the verifiable consent of your parent or lawful "
                "guardian before we process your data. We don't track or monitor children's "
                "behaviour, or show them targeted advertising.",
            ),
        ]
    blocks += [
        Block("h2", "Your rights"),
        Block(
            "bullets",
            items=[
                "Ask for a summary of the personal data we hold about you.",
                "Ask us to correct, complete, update or erase your personal data.",
                "Withdraw your consent at any time, as easily as you gave it: use the same "
                "screen or channel, or write to the contact below.",
                "Nominate someone to exercise these rights if you die or can't act yourself.",
                "Raise a grievance with us, and then complain to the Data Protection Board of "
                "India.",
            ],
        ),
        Block("h2", "Contact us"),
        Block("p", _answer(facts, "INFO-CONTACT")),
    ]
    return blocks


def _breach_playbook(facts: EngagementFacts, register: Register) -> list[Block]:
    contact = _answer(facts, "INFO-CONTACT", "[Name the incident owner]")
    systems = (
        _join(v.get("name") for v in facts.vendors)
        if facts.vendors
        else _answer(facts, "INFO-TOOLS", "list systems")
    )
    return [
        Block("h2", "Roles"),
        Block("p", f"Incident owner: {contact}. Name a deputy and a technical lead."),
        Block("h2", "Steps"),
        Block(
            "bullets",
            items=[
                "Detect and log: record when the company became aware of the breach. That "
                "time starts the clock.",
                "Contain: stop further exposure, revoke access, preserve evidence.",
                f"Assess: what data, how many people, which systems ({systems}).",
                "Tell the Data Protection Board without delay: what happened, when, the likely "
                "impact (Section 8(6), Rule 7).",
                "Tell each affected person without delay, in plain language: what happened, the "
                "likely consequences, what you are doing, what they can do, and who to contact.",
                "Send the Board a detailed report within 72 hours of becoming aware: facts, "
                "cause, people affected, mitigation, and the notices sent to people.",
                "Check whether the incident also has to be reported to CERT-In, whose directions "
                "require certain cyber incidents to be reported within 6 hours.",
                "Remediate and review: fix the root cause and record lessons learned.",
            ],
        ),
        Block("h2", "Timeline"),
        Block(
            "table",
            headers=["When", "What", "Who"],
            rows=[
                [
                    "Hour 0",
                    "Breach becomes known; log it in the breach register",
                    "Whoever finds it",
                ],
                ["Within 6 hours", "Check CERT-In reporting", "Technical lead"],
                ["Without delay", "Intimate the Board; tell affected people", "Incident owner"],
                ["Within 72 hours", "Detailed report to the Board", "Incident owner"],
                ["After closure", "Lessons learned; update controls", "Incident owner"],
            ],
        ),
        Block("h2", "Records to keep"),
        Block("p", "Keep a log of every incident, decision, notification and timestamp."),
    ]


def _dpa(facts: EngagementFacts, register: Register) -> list[Block]:
    processors = _join(v.get("name") for v in facts.vendors) or "[vendor name]"
    blocks = [
        Block("h2", "Parties"),
        Block("p", f"Data Fiduciary: {facts.client}. Data Processor: {processors}."),
        Block("h2", "Scope of processing"),
        Block(
            "table",
            headers=["Item", "Details"],
            rows=[
                ["Personal data", _answer(facts, "INFO-DATA")],
                ["Purposes", _answer(facts, "INFO-PURPOSE")],
                ["Duration and deletion", _answer(facts, "INFO-RETENTION")],
            ],
        ),
        Block("h2", "Processor obligations (outline for the lawyer)"),
        Block(
            "bullets",
            items=[
                "Process personal data only on the Data Fiduciary's documented instructions.",
                "Apply reasonable security safeguards and report breaches without delay.",
                "Delete or return personal data at the end of the engagement.",
                "Engage sub-processors only with prior approval.",
                "Support the Data Fiduciary with Data Principal requests.",
            ],
        ),
    ]
    for v in facts.vendors:
        blocks += [
            Block("h3", f"Schedule {v.get('ref', '')}: {v.get('name', '')}"),
            Block(
                "table",
                headers=["Item", "Details"],
                rows=[
                    ["Service", v.get("service", "") or "-"],
                    ["Personal data shared", v.get("data_shared", "") or "-"],
                    ["Where it is processed", _where(v)],
                    ["Contract status", CONTRACTS.get(v.get("contract", ""), "Unknown")],
                    ["Vendor contact", v.get("contact", "") or "-"],
                ],
            ),
        ]
    return blocks


def _yes_no(facts: EngagementFacts, question_id: str) -> str:
    return {"yes": "Yes", "no": "No", "not_sure": "Not sure"}.get(
        facts.answers.get(question_id, ""), "[Not answered]"
    )


def to_docx(blocks: list[Block]) -> bytes:
    doc = DocxDocument()
    for b in blocks:
        if b.kind == "h1":
            doc.add_heading(b.text, level=0)
        elif b.kind == "h2":
            doc.add_heading(b.text, level=1)
        elif b.kind == "h3":
            doc.add_heading(b.text, level=2)
        elif b.kind == "p":
            doc.add_paragraph(b.text)
        elif b.kind == "warning":
            doc.add_paragraph().add_run(b.text).bold = True
        elif b.kind == "bullets":
            for item in b.items:
                doc.add_paragraph(item, style="List Bullet")
        elif b.kind == "table":
            table = doc.add_table(rows=1, cols=len(b.headers))
            table.style = "Table Grid"
            for cell, header in zip(table.rows[0].cells, b.headers, strict=True):
                cell.text = header
            for row in b.rows:
                for cell, value in zip(table.add_row().cells, row, strict=True):
                    cell.text = value
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
