"""Draft documents built from the intake answers and findings.

Each document is a list of blocks. The same blocks render to the HTML review
preview and to the exported .docx, so the reviewer approves exactly what gets
exported. Templates here decide structure only; the content comes from the
engagement.
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field
from datetime import date

from docx import Document as DocxDocument

from grc_agent.assessment import readiness_score
from grc_agent.register import Register

DOCUMENT_TYPES = {
    "gap_report": "Gap assessment report",
    "ropa": "Record of processing activities",
    "privacy_notice": "Privacy notice",
    "breach_playbook": "Breach response playbook",
    "dpa": "Data processing agreement",
}

DRAFT_BANNER = "DRAFT: generated by the GRC agent. A consultant must review it before it's sent."
DPA_BANNER = (
    "DRAFT FOR LAWYER: not client-ready without legal sign-off. Contract terms here are a "
    "starting point only."
)
STATUS_LABELS = {
    "gap": "Gap",
    "compliant": "Compliant",
    "open_item": "Open item",
    "not_applicable": "Not applicable",
}


@dataclass
class Block:
    kind: str  # h1 | h2 | p | bullets | table | warning
    text: str = ""
    items: list[str] = field(default_factory=list)
    headers: list[str] = field(default_factory=list)
    rows: list[list[str]] = field(default_factory=list)


@dataclass(frozen=True)
class EngagementFacts:
    client: str
    sector: str
    answers: dict[str, str]
    findings: list[
        dict
    ]  # rows with obligation_id, status, severity, citation, summary, remediation


def build_document(kind: str, facts: EngagementFacts, register: Register) -> list[Block]:
    builders = {
        "gap_report": _gap_report,
        "ropa": _ropa,
        "privacy_notice": _privacy_notice,
        "breach_playbook": _breach_playbook,
        "dpa": _dpa,
    }
    blocks = [
        Block("h1", f"{DOCUMENT_TYPES[kind]}: {facts.client}"),
        Block("warning", DPA_BANNER if kind == "dpa" else DRAFT_BANNER),
        Block("p", f"Prepared {date.today():%d %B %Y}. Register version {register.version}."),
    ]
    return blocks + builders[kind](facts, register)


def _answer(facts: EngagementFacts, question_id: str, fallback: str = "[Not provided]") -> str:
    value = (facts.answers.get(question_id) or "").strip()
    return value or fallback


def _lines(text: str) -> list[str]:
    parts = [p.strip(" -•\t") for p in text.replace(";", "\n").replace(",", "\n").splitlines()]
    return [p for p in parts if p] or ["[Not provided]"]


def _gap_report(facts: EngagementFacts, register: Register) -> list[Block]:
    findings = facts.findings
    counts = {s: sum(f["status"] == s for f in findings) for s in STATUS_LABELS}
    score = readiness_score(findings)
    blocks = [
        Block("h2", "Summary"),
        Block(
            "p",
            f"Sector: {facts.sector}. Readiness score: "
            f"{'n/a' if score is None else f'{score}/100'}. "
            f"{counts['gap']} gap(s), {counts['open_item']} open item(s), "
            f"{counts['compliant']} compliant, {counts['not_applicable']} not applicable.",
        ),
        Block(
            "p",
            "Open items are questions the client skipped or wasn't sure about. They are not "
            "passes and need follow-up.",
        ),
    ]
    obligations = {o.id: o for o in register.obligations}
    for severity in ("critical", "high", "medium", "low"):
        rows = [
            [
                f["obligation_id"],
                obligations[f["obligation_id"]].obligation,
                STATUS_LABELS[f["status"]],
                f["citation"],
                f["remediation"] or "-",
            ]
            for f in findings
            if f["severity"] == severity and f["status"] in {"gap", "open_item"}
        ]
        if rows:
            blocks.append(Block("h2", f"{severity.title()} severity"))
            blocks.append(
                Block(
                    "table",
                    headers=["ID", "Obligation", "Status", "Provision", "Next step"],
                    rows=rows,
                )
            )
    return blocks


def _ropa(facts: EngagementFacts, register: Register) -> list[Block]:
    return [
        Block("h2", "Organisation"),
        Block("p", f"{facts.client} ({facts.sector})."),
        Block("h2", "Processing activities"),
        Block(
            "table",
            headers=["Item", "Details from intake"],
            rows=[
                ["Personal data collected", _answer(facts, "INFO-DATA")],
                ["Purposes", _answer(facts, "INFO-PURPOSE")],
                ["Tools and processors", _answer(facts, "INFO-TOOLS")],
                ["Retention", _answer(facts, "INFO-RETENTION")],
                ["Children's data", _yes_no(facts, "CTX-CHILDREN")],
                ["Services outside India", _yes_no(facts, "CTX-FOREIGN")],
                ["Contact for data questions", _answer(facts, "INFO-CONTACT")],
            ],
        ),
        Block(
            "p",
            "Consultant: split this into one row per processing activity, with its own purpose, "
            "data categories, recipients and retention period.",
        ),
    ]


def _privacy_notice(facts: EngagementFacts, register: Register) -> list[Block]:
    return [
        Block("h2", "What we collect"),
        Block("bullets", items=_lines(_answer(facts, "INFO-DATA"))),
        Block("h2", "Why we use it"),
        Block("bullets", items=_lines(_answer(facts, "INFO-PURPOSE"))),
        Block("h2", "Who we share it with"),
        Block("p", _answer(facts, "INFO-TOOLS")),
        Block("h2", "How long we keep it"),
        Block("p", _answer(facts, "INFO-RETENTION")),
        Block("h2", "Your rights"),
        Block(
            "bullets",
            items=[
                "Ask for a summary of the personal data we hold about you.",
                "Ask us to correct, complete, update or erase your personal data.",
                "Withdraw your consent at any time, as easily as you gave it.",
                "Raise a grievance with us, and then with the Data Protection Board of India.",
            ],
        ),
        Block("h2", "Contact us"),
        Block("p", _answer(facts, "INFO-CONTACT")),
    ]


def _breach_playbook(facts: EngagementFacts, register: Register) -> list[Block]:
    contact = _answer(facts, "INFO-CONTACT", "[Name the incident owner]")
    return [
        Block("h2", "Roles"),
        Block("p", f"Incident owner: {contact}. Name a deputy and a technical lead."),
        Block("h2", "Steps"),
        Block(
            "bullets",
            items=[
                "Detect and log: record when and how the incident was found.",
                "Contain: stop further exposure, revoke access, preserve evidence.",
                "Assess: what data, how many people, which systems "
                f"({_answer(facts, 'INFO-TOOLS', 'list systems')}).",
                "Notify the Data Protection Board and each affected person in the form and "
                "timeline the Rules require. Consultant: insert the current timelines.",
                "Remediate and review: fix the root cause and record lessons learned.",
            ],
        ),
        Block("h2", "Records to keep"),
        Block("p", "Keep a log of every incident, decision, notification and timestamp."),
    ]


def _dpa(facts: EngagementFacts, register: Register) -> list[Block]:
    return [
        Block("h2", "Parties"),
        Block("p", f"Data Fiduciary: {facts.client}. Data Processor: [vendor name]."),
        Block("h2", "Scope of processing"),
        Block(
            "table",
            headers=["Item", "Details"],
            rows=[
                ["Personal data", _answer(facts, "INFO-DATA")],
                ["Purposes", _answer(facts, "INFO-PURPOSE")],
                ["Duration and deletion", _answer(facts, "INFO-RETENTION")],
            ],
        ),
        Block("h2", "Processor obligations (outline for the lawyer)"),
        Block(
            "bullets",
            items=[
                "Process personal data only on the Data Fiduciary's documented instructions.",
                "Apply reasonable security safeguards and report breaches without delay.",
                "Delete or return personal data at the end of the engagement.",
                "Engage sub-processors only with prior approval.",
                "Support the Data Fiduciary with Data Principal requests.",
            ],
        ),
    ]


def _yes_no(facts: EngagementFacts, question_id: str) -> str:
    return {"yes": "Yes", "no": "No", "not_sure": "Not sure"}.get(
        facts.answers.get(question_id, ""), "[Not answered]"
    )


def to_docx(blocks: list[Block]) -> bytes:
    doc = DocxDocument()
    for b in blocks:
        if b.kind == "h1":
            doc.add_heading(b.text, level=0)
        elif b.kind == "h2":
            doc.add_heading(b.text, level=1)
        elif b.kind == "p":
            doc.add_paragraph(b.text)
        elif b.kind == "warning":
            doc.add_paragraph().add_run(b.text).bold = True
        elif b.kind == "bullets":
            for item in b.items:
                doc.add_paragraph(item, style="List Bullet")
        elif b.kind == "table":
            table = doc.add_table(rows=1, cols=len(b.headers))
            table.style = "Table Grid"
            for cell, header in zip(table.rows[0].cells, b.headers, strict=True):
                cell.text = header
            for row in b.rows:
                for cell, value in zip(table.add_row().cells, row, strict=True):
                    cell.text = value
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
